[tools]
uv = '0.7.5' # tracked via GitHub Actions workflow

[settings]
experimental = true
python.uv_venv_auto = true # point python to local .venv python
idiomatic_version_file = false # do not infer tools from other files such as .python-version
