prompt:
    uv run python src/finances/prompt_current_amounts.py
crypto:
    bash src/finances/crypto.sh
run: clean monthly depot graph
clean:
    #!/bin/sh
    today=$(date +%Y-%m-%d)
    echo "Creating fresh folder data/output/$today"
    rm -rf data/output/$today/* && mkdir -p data/output/$today
monthly:
    #!/bin/sh
    today=$(date +%Y-%m-%d)
    uv run python src/finances/evaluate_expenses.py >> data/output/$today/summary.md
depot:
    uv run python src/finances/parse_depot.py
graph:
    #!/bin/sh
    today=$(date +%Y-%m-%d)
    uv run python src/finances/graphs.py >> data/output/$today/summary.md