[project]
name = "finances"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "graphviz>=0.20.3",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "toml>=0.10.2",
]
